# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://coaching-true-connections.github.io'
baseurl: ''
title: 'True Connections Coaching'
description: 'Coaching in Sandpoint, ID'
permalink: pretty
logo: "/images/logo.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  - title: Home
    url: /
  - title: About
    url: /about-us/
  - title: Coaching Services
    url: /coaching-services/
  - title: Consulting Services
    url: /consulting-services/
  - title: How It Works
    url: /how-it-works/
  - title: FAQ
    url: /faq/
  - title: Testimonials
    url: /testimonials/
  - title: Contact / Book a Call
    url: /contact-us/
    
# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"
- title: About Us
  url: /about-us/
- title: Contact Us
  url: /contact-us/


